# Generated by Django 2.0.4 on 2018-05-31 21:07

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT_TITLE', max_length=60)),
                ('songamount', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('cover', models.FileField(blank=True, null=True, upload_to='')),
                ('pubdate', models.DateTimeField(verbose_name='date published')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='author', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Artist'),
        ),
    ]
