# Generated by Django 2.0.4 on 2018-05-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
    ]
