# Generated by Django 2.0.4 on 2018-05-31 22:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_album_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug2',
            field=autoslug.fields.AutoSlugField(default='DEFAULT_TITLE', editable=False, populate_from='title'),
        ),
    ]
