# Generated by Django 2.0.4 on 2018-06-08 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_album_slug2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='slug2',
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
